function population_after_local_search = hybridization( ...
            population, ...
            genome_length, ...
            fitness_function, ...
            domain_start, domain_end,...
            wind1, wind2)
%     evaluate offspring fitness
% for each chromosome
% mutate
% evaluate fitness
% keep if better
    population_after_local_search = population;
    population_after_local_search(wind1, :) = local_search_via_gene_flip( ...
        population_after_local_search(wind1, :), ...
        genome_length, ...
        fitness_function, ...
        domain_start, ...
        domain_end);
end

