function newpop = sharing( ...
  population, ...
  population_size, ...
  genome_length, ...
  option, ...
  sigmash, ...
  alpha ...
)

  newpop = population;

  for i = 1:population_size
    for j = 1: population_size
      d(i,j)=abs(newpop(i, genome_length + 1) - newpop(j, genome_length + 1));
      if d(i,j) < sigmash & sigmash ~= 0
        sh(j) = 1 - (d(i,j) / sigmash) ^ alpha;
      else
        sh(j) = 0;
      end
    end
    newpop(i, genome_length + 2) = newpop(i, genome_length + 2) / sum(sh);
  end
